"""Cambio de las relaciones

Revision ID: 0d3082d006ab
Revises: 9d61e5d8675d
Create Date: 2025-11-26 18:51:27.378463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d3082d006ab'
down_revision: Union[str, None] = '9d61e5d8675d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
