"""se agrego el stock

Revision ID: 9d18044f32a1
Revises: 2ac9aecca34a
Create Date: 2025-11-28 17:13:39.528161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d18044f32a1'
down_revision: Union[str, None] = '2ac9aecca34a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('stock', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_products_stock'), 'products', ['stock'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_stock'), table_name='products')
    op.drop_column('products', 'stock')
    # ### end Alembic commands ###
