"""se cambiaron los nombres de las relaciones

Revision ID: 9d61e5d8675d
Revises: 54fb45de6de3
Create Date: 2025-11-26 18:42:10.194105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d61e5d8675d'
down_revision: Union[str, None] = '54fb45de6de3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
